### ISSUE TITLE
FBNeo crashes when loading a second game

### ISSUE THREAD

**Issue by kivutar** [libretro/ludo#214]
How to reproduce:
 - Load any FBA game
 - Load a second FBA game

```
ludo(3035,0x8cfe5c0) malloc: *** error for object 0x7928e00: pointer being freed was not allocated
ludo(3035,0x8cfe5c0) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff7b99f2c6 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4347b90, 0xc001e79ba0, 0xc00491cea0)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc001e79b70 sp=0xc001e79b38 pc=0x4005a7b
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_load_game(0x1a795a10, 0xc00491cea0, 0xc001e93100)
	_cgo_gotypes.go:413 +0x4a fp=0xc001e79ba0 sp=0xc001e79b70 pc=0x42895ea
github.com/libretro/ludo/libretro.(*Core).LoadGame.func1(0xc0036c40c0, 0xc00491cea0, 0x4a0f930)
	/Users/kivutar/ludo/libretro/libretro.go:388 +0xdb fp=0xc001e79be0 sp=0xc001e79ba0 pc=0x428c66b
github.com/libretro/ludo/libretro.(*Core).LoadGame(0xc0036c40c0, 0xc001a4b030, 0x3a, 0x10b7f8, 0x0, 0x0)
	/Users/kivutar/ludo/libretro/libretro.go:388 +0x97 fp=0xc001e79c10 sp=0xc001e79be0 pc=0x428b557
github.com/libretro/ludo/core.LoadGame(0xc001a4b030, 0x3a, 0x1a, 0x1)
	/Users/kivutar/ludo/core/core.go:143 +0x11a fp=0xc001e79d08 sp=0xc001e79c10 pc=0x42fe55a
github.com/libretro/ludo/menu.loadEntry(0xc0023160e0, 0xc00231e01f, 0x17, 0xc001a4b030, 0x3a)
	/Users/kivutar/ludo/menu/scene_playlist.go:81 +0x1c7 fp=0xc001e79db8 sp=0xc001e79d08 pc=0x432a5c7
github.com/libretro/ludo/menu.buildPlaylist.func1()
	/Users/kivutar/ludo/menu/scene_playlist.go:35 +0x4e fp=0xc001e79df0 sp=0xc001e79db8 pc=0x4334a5e
github.com/libretro/ludo/menu.genericInput(0xc0023160e0, 0x3c8f3fd9)
	/Users/kivutar/ludo/menu/input.go:79 +0x21c fp=0xc001e79e10 sp=0xc001e79df0 pc=0x43229ac
github.com/libretro/ludo/menu.(*scenePlaylist).update(0xc0023160e0, 0x13c8f3fd9)
	/Users/kivutar/ludo/menu/scene_playlist.go:114 +0x39 fp=0xc001e79e30 sp=0xc001e79e10 pc=0x432ac09
github.com/libretro/ludo/menu.(*Menu).Update(...)
	/Users/kivutar/ludo/menu/input.go:22
main.runLoop(0xc000574100, 0xc002304040)
	/Users/kivutar/ludo/main.go:48 +0x201 fp=0xc001e79eb8 sp=0xc001e79e30 pc=0x4337f51
main.main()
	/Users/kivutar/ludo/main.go:126 +0x692 fp=0xc001e79f98 sp=0xc001e79eb8 pc=0x4338642
runtime.main()
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:200 +0x20c fp=0xc001e79fe0 sp=0xc001e79f98 pc=0x402fb8c
runtime.goexit()
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001e79fe8 sp=0xc001e79fe0 pc=0x405a061

goroutine 6 [chan receive]:
github.com/libretro/ludo/core.Init.func1(0xc000314af0)
	/Users/kivutar/ludo/core/core.go:37 +0x59
created by github.com/libretro/ludo/core.Init
	/Users/kivutar/ludo/core/core.go:36 +0x61

rax    0x0
rbx    0x8cfe5c0
rcx    0x7ffeefbff088
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbff0c0
rsp    0x7ffeefbff088
r8     0x0
r9     0x7ffeefbfefe0
r10    0x0
r11    0x206
r12    0x307
r13    0x16f6a000
r14    0x6
r15    0x2d
rip    0x7fff7b99f2c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
```

It doesn't happen on RA

**Comment by kivutar** [comment]
Related to https://github.com/libretro/FBNeo/issues/165

**Comment by kivutar** [comment]
Resolved
