### ISSUE TITLE
Got an error trying to load Ludo

### ISSUE THREAD

**Issue by Dhamma-valence** [libretro/ludo#373]
This only occurs when I have my Xbox One controller connected and then start Ludo.
Occurs both in the most recent stable release and when compiled from source.

GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 050000005e040000e002000003090000 (Xbox One Wireless Controller)
GLFW: Please report this bug in the Go package immediately.

https://gist.github.com/Dhamma-valence/ca8e0dfa305302af153d2d0ecaf9ef91

**Comment by johnnyq** [comment]
Hi @Dhamma-valence What OS and CPU are you using?

**Comment by kivutar** [comment]
If I remember well, this is the second time that a bug is reported about the Go binding of GLFW crashing on some joypads being plugged.

**Comment by Dhamma-valence** [comment]
Debian Bullseye, Intel i7 7700k (amd64 arch)

**Comment by kivutar** [comment]
I don't want to dive too much into GLFW. I think they will fix this bug by themselves and we will get the fix in a dependency update.

**Comment by kivutar** [comment]
This should be fixed with the last GLFW update. If not, please reopen.

**Comment by lostfictions** [comment]
Hey @kivutar, I'm getting a similar error in Ludo `v0.16.7` on Ubuntu 20.04 with a Dualshock 4. With the DS4 connected it crashes on launch with no visible error message -- unless I run it from a terminal, in which case I get:

```
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)
GLFW: Please report this bug in the Go package immediately.
```
The above is printed 30 or 40 times, then:
```
panic: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x2190590)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/error.go:174 +0x225
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/error.go:185
github.com/go-gl/glfw/v3.3/glfw.SetJoystickCallback(0xa28a60, 0x49794)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/input.go:569 +0x65
github.com/libretro/ludo/input.Init(0xc00017e090)
	/home/runner/work/ludo/ludo/input/input.go:73 +0x6d
main.main()
	/home/runner/work/ludo/ludo/main.go:128 +0x4e6
```

If I disconnect the DS4 it launches fine. I can then connect the DS4 and it'll be detected and work for the menus. But as soon as I try to launch a game it crashes with this:

```
goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc0023f5ae8, 0x2ab44d0)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/error.go:174 +0x225
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/error.go:185
github.com/go-gl/glfw/v3.3/glfw.SetJoystickCallback(0xa28a60, 0x49794)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210727001814-0db043d8d5be/input.go:569 +0x65
github.com/libretro/ludo/input.Init(0xc006952000)
	/home/runner/work/ludo/ludo/input/input.go:73 +0x6d
github.com/libretro/ludo/core.LoadGame(0xc003a41f20, 0x37, 0x0, 0x0)
	/home/runner/work/ludo/ludo/core/core.go:175 +0x225
github.com/libretro/ludo/menu.loadPlaylistEntry(0xc000128480, 0xc006317104, 0x2e, 0xc003a41f20, 0x37, 0xc003a41f57, 0x18, 0x2e8034ab)
	/home/runner/work/ludo/ludo/menu/scene_playlist.go:107 +0x1ac
github.com/libretro/ludo/menu.buildPlaylist.func1()
	/home/runner/work/ludo/ludo/menu/scene_playlist.go:35 +0x75
github.com/libretro/ludo/menu.genericInput(0xc000128480, 0x3ca0dae7)
	/home/runner/work/ludo/ludo/menu/input.go:92 +0x728
github.com/libretro/ludo/menu.(*scenePlaylist).update(0xc000128480, 0x43ca0dae7)
	/home/runner/work/ludo/ludo/menu/scene_playlist.go:187 +0x39
github.com/libretro/ludo/menu.(*Menu).Update(...)
	/home/runner/work/ludo/ludo/menu/input.go:24
main.runLoop(0xc006952000, 0xc002584480)
	/home/runner/work/ludo/ludo/main.go:61 +0x40f
main.main()
	/home/runner/work/ludo/ludo/main.go:149 +0x525
```
