### ISSUE TITLE
Libretro ppsspp looking for ideas

### ISSUE THREAD

**Issue by takov751** [libretro/ludo#489]
I have built the latest libretro build of ppsspp and it does load of course missing some config, but what's cryptic about it that it does fails to load assets which was moved to ludo assets directory and fails to open ISO . 
```

ThreadManager::Init(compute threads: 4, all: 8)
2022/07/25 18:14:06 [ERROR]: [IO] Missing filesystem for lang/.ini
2022/07/25 18:14:06 [INFO]: [G3D] Longest display side: -1 pixels. Choosing scale 1
2022/07/25 18:14:06 [ERROR]: [IO] Missing filesystem for 'langregion.ini'
2022/07/25 18:14:06 [ERROR]: [LOADER] Failed to read /controls.ini. Setting controller config to default.
2022/07/25 18:14:06 [Core]: Name: PPSSPP
2022/07/25 18:14:06 [Core]: Version: v1.12.3-1443-gd2a3918f5
2022/07/25 18:14:06 [Core]: Valid extensions: elf|iso|cso|prx|pbp
2022/07/25 18:14:06 [Core]: Need fullpath: true
2022/07/25 18:14:06 [Core]: Block extract: false
2022/07/25 18:14:36 [Video]: Set Pixel Format: 1
2022/07/25 18:14:36 [OpenAL]: Using 4 buffers of 8192 bytes.
2022/07/25 18:14:36 [Core]: Game loaded: /storage/Retro/roms/God of War - Ghost of Sparta.ISO
2022/07/25 18:14:36 [ERROR]: [IO] Couldn't read data for 'ppge_atlas.zim'
2022/07/25 18:14:36 [ERROR]: [SCEGE] Failed to load ppge_atlas.zim.

Place it in the directory "assets" under your PPSSPP directory.

PPGe stuff will not be drawn.
2022/07/25 18:14:36 [ERROR]: [FILESYS] Can't open file '/sce_lbn0x9a820_size0xff18' with write access on an ISO partition
2022/07/25 18:14:36 [ERROR]: [SCEIO] 8001b004=sceIoOpen(disc0:/sce_lbn0x9a820_size0xff18, 3, 0)
2022/07/25 18:14:37 [ERROR]: [FILESYS] Can't open file '/sce_lbn0x47700_size0x704dc' with write access on an ISO partition
2022/07/25 18:14:37 [ERROR]: [SCEIO] 8001b004=sceIoOpen(disc0:/sce_lbn0x47700_size0x704dc, 3, 0)
SIGILL: illegal instruction
PC=0x9cc18 m=0 sigcode=1
signal arrived during cgo execution
instruction bytes: 0xfe 0xff 0xff 0xea 0x7d 0x62 0x4d 0x0 0xe2 0x6e 0x4f 0x0 0x94 0xb7 0x4f 0x0

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43f0a8, 0x1444ed4)
        /opt/hostedtoolcache/go/1.17.11/x64/src/runtime/cgocall.go:156 +0x5c fp=0x1444ebc sp=0x1444ea4 pc=0x51258
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_run(0x8c162985)
        _cgo_gotypes.go:610 +0x2c fp=0x1444ed0 sp=0x1444ebc pc=0x29c3d0
github.com/libretro/ludo/libretro.(*Core).Run.func1(0x460a0e0)
        /home/runner/work/ludo/ludo/libretro/libretro.go:502 +0x48 fp=0x1444ee8 sp=0x1444ed0 pc=0x29dce4
github.com/libretro/ludo/libretro.(*Core).Run(0x460a0e0)        /home/runner/work/ludo/ludo/libretro/libretro.go:502 +0x1c fp=0x1444ef0 sp=0x1444ee8 pc=0x29dc8c
main.runLoop(0x3dc7f10, 0x14ae120)
        /home/runner/work/ludo/ludo/main.go:47 +0x328 fp=0x1444f58 sp=0x1444ef0 pc=0x425d38
main.main()
        /home/runner/work/ludo/ludo/main.go:149 +0x640 fp=0x1444fbc sp=0x1444f58 pc=0x426510
runtime.main()
        /opt/hostedtoolcache/go/1.17.11/x64/src/runtime/proc.go:255 +0x278 fp=0x1444fe4 sp=0x1444fbc pc=0x870e0
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.11/x64/src/runtime/asm_arm.s:838 +0x4 fp=0x1444fe4 sp=0x1444fe4 pc=0xb6088

trap    0x6
error   0x0
oldmask 0x1000
r0      0x3c
r1      0x0
r2      0x3030303
r3      0x3030303
r4      0x853c3010
r5      0x404003e
r6      0x3e
r7      0x8cac7670
r8      0x8cac7730
r9      0x853ca010
r10     0x8371b0
fp      0x148c
ip      0x8cac779c
sp      0xbe918478
lr      0x8c1e053e
pc      0x9cc18
cpsr    0x30
fault   0x6d616e58

```

Any idea if where should I look or if it's even solvable at this point of time

**Comment by kivutar** [comment]
It's because ppsspp only works on the kivutar/gl branch of ludo so far. And this branch is not really ready to be merged yet, it causes some bugs on other emulators.

**Comment by takov751** [comment]
Thanks for the answer 👌👌
