### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Shadowblitz16** [libretro/ludo#512]
```
2023/08/20 12:42:11 Can't load game database: open ./database: no such file or directory
panic: open assets/font.ttf: no such file or directory

goroutine 1 [running, locked to thread]:
github.com/libretro/ludo/video.(*Video).Configure(0xc000000e60, 0xa?)
        /home/runner/work/ludo/ludo/video/video.go:127 +0x985
github.com/libretro/ludo/video.Init(...)
        /home/runner/work/ludo/ludo/video/video.go:51
main.main()
        /home/runner/work/ludo/ludo/main.go:120 +0x45b
```

**Comment by kivutar** [comment]
You need to clone recursively
